export interface Effect {
  id: number;
  name: string;
  category: string;
}

export const EFFECTS: Effect[] = [
  { id: 0, name: 'Обычный', category: 'Базовые' },
  // Glitch / Datamoshing
  { id: 1, name: 'RGB Разделение', category: 'Глитч' },
  { id: 2, name: 'Сортировка пикселей', category: 'Глитч' },
  { id: 3, name: 'Датамош', category: 'Глитч' },
  { id: 4, name: 'Сканлайны', category: 'Глитч' },
  { id: 5, name: 'CRT Искажение', category: 'Глитч' },
  { id: 6, name: 'Цифровой глитч', category: 'Глитч' },
  { id: 7, name: 'VHS Кассета', category: 'Глитч' },
  { id: 8, name: 'Хроматическая аберрация', category: 'Глитч' },
  { id: 9, name: 'След кадра', category: 'Глитч' },
  { id: 10, name: 'Шум и зерно', category: 'Глитч' },
  { id: 58, name: 'Блочный глитч', category: 'Глитч' },
  { id: 59, name: 'Разрыв цвета', category: 'Глитч' },
  { id: 60, name: 'VCR Трекинг', category: 'Глитч' },
  { id: 61, name: 'JPEG Артефакты', category: 'Глитч' },
  { id: 62, name: 'Смещение времени', category: 'Глитч' },
  { id: 87, name: 'Шумный RGB', category: 'Глитч' },
  { id: 90, name: 'Негатив + Глитч', category: 'Глитч' },
  { id: 94, name: 'Телепомехи', category: 'Глитч' },
  { id: 100, name: 'Случайные блоки', category: 'Глитч' },
  { id: 101, name: 'Смещение каналов', category: 'Глитч' },
  // Color Dynamics
  { id: 11, name: 'Стробоскоп', category: 'Цвет' },
  { id: 12, name: 'Инфракрасный', category: 'Цвет' },
  { id: 13, name: 'Тепловизор', category: 'Цвет' },
  { id: 14, name: 'Психоделика', category: 'Цвет' },
  { id: 15, name: 'Инверсия', category: 'Цвет' },
  { id: 16, name: 'Сепия', category: 'Цвет' },
  { id: 17, name: 'Сдвиг оттенка', category: 'Цвет' },
  { id: 18, name: 'Дуотон', category: 'Цвет' },
  { id: 19, name: 'Неоновое свечение', category: 'Цвет' },
  { id: 20, name: 'Квантование цвета', category: 'Цвет' },
  { id: 63, name: 'Киберпанк', category: 'Цвет' },
  { id: 64, name: 'Vaporwave', category: 'Цвет' },
  { id: 65, name: 'Золотой час', category: 'Цвет' },
  { id: 66, name: 'Матрица (Зеленый)', category: 'Цвет' },
  { id: 67, name: 'Кроваво-красный', category: 'Цвет' },
  { id: 68, name: 'Глубокий синий', category: 'Цвет' },
  { id: 69, name: 'Радужный цикл', category: 'Цвет' },
  { id: 70, name: 'Соляризация', category: 'Цвет' },
  { id: 96, name: 'Инфракрасный (Красный)', category: 'Цвет' },
  { id: 97, name: 'Дальтонизм (Симуляция)', category: 'Цвет' },
  { id: 103, name: 'Взрыв цвета', category: 'Цвет' },
  // Flicker / Strobe
  { id: 51, name: 'RGB Стробоскоп', category: 'Мерцание' },
  { id: 52, name: 'Мерцание яркости', category: 'Мерцание' },
  { id: 53, name: 'Инверсия (Стробоскоп)', category: 'Мерцание' },
  { id: 54, name: 'Вспышки оттенков', category: 'Мерцание' },
  { id: 55, name: 'ЧБ Стробоскоп', category: 'Мерцание' },
  { id: 56, name: 'Глитч-мерцание', category: 'Мерцание' },
  { id: 57, name: 'Шумовое мерцание', category: 'Мерцание' },
  // Artistic
  { id: 21, name: 'Постеризация', category: 'Арт' },
  { id: 22, name: 'ASCII Арт', category: 'Арт' },
  { id: 23, name: 'Контуры (Sobel)', category: 'Арт' },
  { id: 24, name: 'Полутона', category: 'Арт' },
  { id: 25, name: 'Карандашный набросок', category: 'Арт' },
  { id: 26, name: 'Масляная живопись', category: 'Арт' },
  { id: 27, name: 'Комикс', category: 'Арт' },
  { id: 28, name: 'Тиснение', category: 'Арт' },
  { id: 29, name: 'Штриховка', category: 'Арт' },
  { id: 30, name: 'Акварель', category: 'Арт' },
  { id: 71, name: 'Светящиеся края', category: 'Арт' },
  { id: 72, name: 'Toon Шейдер', category: 'Арт' },
  { id: 73, name: 'Пуантилизм', category: 'Арт' },
  { id: 74, name: 'CRT Фосфор', category: 'Арт' },
  { id: 75, name: 'Дизеринг', category: 'Арт' },
  { id: 76, name: 'Поп-арт', category: 'Арт' },
  { id: 86, name: 'Цветной ASCII', category: 'Арт' },
  { id: 89, name: 'Цветные полутона', category: 'Арт' },
  { id: 95, name: 'Стекло', category: 'Арт' },
  // Geometry
  { id: 31, name: 'Калейдоскоп', category: 'Геометрия' },
  { id: 32, name: 'Зеркало X', category: 'Геометрия' },
  { id: 33, name: 'Зеркало Y', category: 'Геометрия' },
  { id: 34, name: 'Зеркало Квадро', category: 'Геометрия' },
  { id: 35, name: 'Рыбий глаз', category: 'Геометрия' },
  { id: 36, name: 'Пикселизация', category: 'Геометрия' },
  { id: 37, name: 'Спираль', category: 'Геометрия' },
  { id: 38, name: 'Рябь', category: 'Геометрия' },
  { id: 39, name: 'Выпуклость', category: 'Геометрия' },
  { id: 40, name: 'Сфера', category: 'Геометрия' },
  { id: 77, name: 'Мозаика', category: 'Геометрия' },
  { id: 78, name: 'Волновое искажение', category: 'Геометрия' },
  { id: 79, name: 'Щипок', category: 'Геометрия' },
  { id: 80, name: 'Скручивание', category: 'Геометрия' },
  { id: 81, name: 'Разбитое стекло', category: 'Геометрия' },
  { id: 82, name: 'Рекурсия (Дросте)', category: 'Геометрия' },
  { id: 91, name: 'Жидкий металл', category: 'Геометрия' },
  { id: 99, name: 'Психоделическая рябь', category: 'Геометрия' },
  { id: 104, name: 'Магнитное поле', category: 'Геометрия' },
  // Misc / Combinations
  { id: 41, name: 'Матрица', category: 'Разное' },
  { id: 42, name: 'Ночное видение', category: 'Разное' },
  { id: 43, name: 'Сонное размытие', category: 'Разное' },
  { id: 44, name: 'Виньетка', category: 'Разное' },
  { id: 45, name: 'Радиальное размытие', category: 'Разное' },
  { id: 46, name: 'Зум-размытие', category: 'Разное' },
  { id: 47, name: 'Волны', category: 'Разное' },
  { id: 48, name: 'Глитч + Контуры', category: 'Разное' },
  { id: 49, name: 'Тепловизор + Пиксели', category: 'Разное' },
  { id: 50, name: 'Психоделика + Калейдоскоп', category: 'Разное' },
  { id: 83, name: 'VHS + Стробоскоп', category: 'Разное' },
  { id: 84, name: 'Контуры + Мерцание', category: 'Разное' },
  { id: 85, name: 'Тепловизор + Глитч', category: 'Разное' },
  { id: 88, name: 'ЭЛТ-монитор', category: 'Разное' },
  { id: 92, name: 'Голограмма', category: 'Разное' },
  { id: 93, name: 'Пиксельный шлейф', category: 'Разное' },
  { id: 98, name: 'Эхо', category: 'Разное' },
  { id: 102, name: 'Растворение', category: 'Разное' },
  { id: 105, name: 'Сон', category: 'Разное' },
];
